version: '3.3'
services:
  jenkins-container: 
    image: mirekphd/jenkins-jdk17-on-ubuntu2204
    container_name: jenkins-container
    user: root   
    ports:
      - '80:8080'
    privileged: true
    volumes:
      - ./data:/var/jenkins_home
    restart: on-failure
