version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always # automatically keeps it on when docker starts
    privileged: true
    user: root
    ports:
      - 81:8080
      - 51000:50000
    container_name: jenkins-lts1
    volumes:
      - ~/jenkins_home2:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
