version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always # automatically keeps it on when docker starts
    privileged: true
    user: root
    ports:
      - 80:8080
      - 50000:50000
    container_name: jenkins-lts1
    RUN apt-get -y update; apt-get install -y sudo; apt-get install -y git wget
    RUN echo "Jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
    RUN wget http://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
    RUN tar -xvzf docker-latest.tgz
    RUN mv docker/* /usr/bin/
    USER Jenkins
    volumes:
      - ~/jenkins_home2:/var/jenkins_home      
      - /usr/bin/docker:/usr/bin/docker
